### ISSUE TITLE
Ajuda com  Xdebug

### ISSUE THREAD

**Issue by alan-fernandes** [saraivagilberto/php7-apache-dev#1]
Falae meu caro, 

Estou com dúvida para utilizar o vscode + docker com sua imagem e utilizar o Debug
consegue me ajudar?

version: "2"
services:
  php:
    image: saraivagilberto/php7.2-apache-dev
    container_name: etiquetas
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      WEB_DOCUMENT_ROOT: "/var/www/html"
      WEB_PHP_TIMEOUT: 600
      PHP_DEBUGGER: "xdebug"
      XDEBUG_DEFAULT_ENABLE: 1
      XDEBUG_REMOTE_AUTOSTART: 1
      XDEBUG_REMOTE_CONNECT_BACK: 1
      XDEBUG_REMOTE_ENABLE: 1
      XDEBUG_IDEKEY: "DOCKER"
      XDEBUG_REMOTE_HANDLER: "dbgp"
      XDEBUG_REMOTE_PORT: 9001    
      XDEBUG_REMOTE_HOST: "host.docker.internal"

**Comment by saraivagilberto** [comment]
Opa, acredito que vc vai ter que configurar o vscode na parte de debug -> launch corretamente:
um exemplo que talvez encaixe no que vc precisa:
`.vscode/launch.json`
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Listen for XDebug",
            "type": "php",
            "request": "launch",
            "port": 9001,
            "pathMappings": {
                "/var/www/html": "${workspaceRoot}/",
            }
        }
    ]
}
```

**Comment by alan-fernandes** [comment]
Falae meu caro, muito obrigado pelo retorno, no final era só desativar o connect_back

   WEB_DOCUMENT_ROOT: "/var/www/html"
      WEB_PHP_TIMEOUT: 600
      PHP_DEBUGGER: "xdebug"
      XDEBUG_REMETE_HANDLER: DBPG
      XDEBUG_DEFAULT_ENABLE: 1
      XDEBUG_REMOTE_AUTOSTART: 1
      XDEBUG_REMOTE_CONNECT_BACK: 0
      XDEBUG_REMOTE_ENABLE: 1
      XDEBUG_REMOTE_PORT: 9001  
      XDEBUG_REMOTE_HOST: host.docker.internal

Brigadao!
